export const CHANGE_MAIL_RECIPIENT = 'CHANGE_MAIL_RECIPIENT'
export const CHANGE_MAIL_SUBJECT = 'CHANGE_MAIL_SUBJECT'
export const CHANGE_MAIL_CONTENT = 'CHANGE_MAIL_CONTENT'
export const CHANGE_EDIT_STATUS = 'CHANGE_EDIT_STATUS'
